datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: true

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: tempo
    url: http://tempo:3200
